---
title: Scalaで自作するプログラミング言語処理系
subtitle: Computation Models & Compilers on Scala
topics:
- Scala
- 自作言語
- 構文解析
- 型推論
- ラムダ計算
summary: 本書では、ラムダ計算を理論的背景に持つ独自のプログラミング言語のインタプリタを自作して、計算論の基礎を学ぶ。
chapters:
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
published: true
