---
title: コンテスト運営を支援する自動集計システム
subtitle: Amateur-Radio Contest Administration System
topics:
- アマチュア無線
- コンテスト
- 自動集計
summary: アマチュア無線のコンテストの集計作業を自動化。様々なコンテストに対応。楽しく開催できます。
chapters:
- '1'
- '2'
- '3'
- '4'
published: true
