---
title: うさぎさんでもわかる並列言語Chapel
subtitle: Chapel the Parallel Programming Language
topics:
- Chapel
- 並列プログラミング言語
summary: "[Chapel](https://chapel-lang.org)は、**型推論**と**テンプレート**と**区分化大域アドレス空間**を特徴\
  とし、高度に抽象化された**高生産性並列言語**である。\n"
chapters:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
published: true
