name: 'markdown'
on:
  push:
    branches:
    - 'master'
jobs:
  Compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        book:
        - ats4
        - chpl
        - dusk
        - fava
        - mine
        - wave
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/gradle-build-action@v1
      with:
        arguments: build
        gradle-version: current
        build-root-directory: texmd
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby
    - run: |
        sudo apt install inkscape pdf2svg
        jruby books/mark.rb ${{matrix.book}}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.book}}
        path: ${{matrix.book}}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.book}}-images
        path: images/${{matrix.book}}
  Publish:
    needs: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: nextzlog/fava
        path: fava
    - uses: actions/checkout@v2
      with:
        repository: nextzlog/mine
        path: mine
    - uses: actions/download-artifact@v2
      with:
        path: pages/books
    - run: sudo apt install inkscape pdf2svg
    - run: |
        for f in */*.svg
        do
          inkscape --export-filename="${f%.*}.png" $f
        done
      working-directory:
        files
    - run: |
        for f in *.pdf
        do
          pdf2svg $f "${f%.*}.%02d.svg" all
        done
      working-directory:
        books
    - run: |
        mkdir pages/images
        mv books/*.pdf pages
        mv books/*.*.svg pages/images
        mv files/*/*.png pages/images
        mv pages/books/*/????.md pages
        mv pages/books/*/* pages/books
    - uses: peaceiris/actions-gh-pages@v3
      with:
        cname: pafelog.net
        enable_jekyll: true
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: pages
