name: 'markdown'
on:
  push:
    branches:
    - 'master'
jobs:
  Compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        book:
        - ats4
        - chpl
        - dusk
        - fava
        - mine
        - wave
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/gradle-build-action@v1
      with:
        arguments: build
        gradle-version: current
        build-root-directory: text
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby
    - run: |
        sudo apt install inkscape pdf2svg
        jruby book/mark.rb ${{matrix.book}}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.book}}
        path: ${{matrix.book}}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.book}}-images
        path: images/${{matrix.book}}
  Publish:
    needs: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: nextzlog/fava
        path: fava
    - uses: actions/checkout@v2
      with:
        repository: nextzlog/mine
        path: mine
    - uses: actions/download-artifact@v2
      with:
        path: site/books
    - run: |
        mv book/*.pdf site
        mv site/books/*/????.md site
        mv site/books/*/* site/books
        mv site/scales/* site/images
        mv fava/images/* site/images
        mv mine/images/* site/images
    - run: |
        sudo apt install inkscape pdf2svg
        for f in images/*.svg
        do
          inkscape --export-png="${f%.*}.png" $f
        done
        for p in {01..35}
        do
          pdf2svg zylo.pdf images/zylo.$p.svg $p
        done
      working-directory:
        site
    - uses: peaceiris/actions-gh-pages@v3
      with:
        cname: pafelog.net
        enable_jekyll: true
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: site
