name: 'markdown'
on:
  push:
    branches:
    - 'master'
jobs:
  Compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        book:
        - ats4
        - chpl
        - dusk
        - fava
        - mine
        - wave
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/gradle-build-action@v1
      with:
        arguments: build
        gradle-version: current
        build-root-directory: text
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby
    - run: jruby book/mark.rb ${{matrix.book}}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.book}}
        path: ${{matrix.book}}.md
  Publish:
    needs: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: nextzlog/fava
        path: fava
    - uses: actions/checkout@v2
      with:
        repository: nextzlog/mine
        path: mine
    - uses: actions/download-artifact@v2
      with:
        path: book
    - run: |
        cp book/*/*.md book/*.pdf site
        cp fava/images/* site/images
        cp mine/images/* site/images
    - run: |
        sudo apt install pdf2svg
        for p in {01..35}
        do
          pdf2svg zylo.pdf images/zylo.$p.svg $p
        done
      working-directory:
        site
    - uses: peaceiris/actions-gh-pages@v3
      with:
        cname: pafelog.net
        enable_jekyll: true
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: site
