---
title: D言語で実装する並列スケジューラ入門
subtitle: Parallel Work-Stealing Scheduler on D
topics:
- D
- 並列処理
summary: "**並列処理**とは、長時間を要する計算の内容を分割して複数のプロセッサに分担させ、処理速度の改善を図る技術を指す。"
chapters:
- '1'
- '2'
- '3'
- '4'
- '5'
published: true
